// <auto-generated />
using System;
using DataAccesLayer_DAL_.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccesLayer_DAL_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityLayer.Models.Concrete.DynamicField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DynamicObjectId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicObjectId");

                    b.ToTable("DynamicFields");
                });

            modelBuilder.Entity("EntityLayer.Models.Concrete.DynamicObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DynamicObjects");
                });

            modelBuilder.Entity("EntityLayer.Models.Concrete.TransactionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DynamicFieldId")
                        .HasColumnType("int");

                    b.Property<int?>("DynamicObjectId")
                        .HasColumnType("int");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldId");

                    b.HasIndex("DynamicObjectId");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("EntityLayer.Models.Concrete.DynamicField", b =>
                {
                    b.HasOne("EntityLayer.Models.Concrete.DynamicObject", "DynamicObject")
                        .WithMany("DynamicFields")
                        .HasForeignKey("DynamicObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicObject");
                });

            modelBuilder.Entity("EntityLayer.Models.Concrete.TransactionLog", b =>
                {
                    b.HasOne("EntityLayer.Models.Concrete.DynamicField", "DynamicField")
                        .WithMany()
                        .HasForeignKey("DynamicFieldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityLayer.Models.Concrete.DynamicObject", "DynamicObject")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("DynamicObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DynamicField");

                    b.Navigation("DynamicObject");
                });

            modelBuilder.Entity("EntityLayer.Models.Concrete.DynamicObject", b =>
                {
                    b.Navigation("DynamicFields");

                    b.Navigation("TransactionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
